---

- name: stop and delete webserver
  hosts: all
  become: true

  tasks:
    - name: stop httpd
      service: name=httpd state=stopped
      when: ansible_distribution == 'Amazon'

    - name: delete httpd
      action: "{{ ansible_pkg_mgr }} name=nginx state=absent"
      when: ansible_distribution == 'Amazon'

    - name: stop nginx
      service: name=nginx state=stopped
      when: ansible_distribution == 'Ubuntu'
    
    - name: delete nginx
      action: "{{ ansible_pkg_mgr }} name=nginx state=absent autoremove=yes purge=yes"
      when: ansible_distribution == 'Ubuntu'
